### ISSUE TITLE
Receiving "KeyError: 'done'"

### ISSUE THREAD

**Issue by mattgallivan** [krumiaa/MindMaker#14]
I'm trying to integrate this project into UE5, Preview 1. It's all going well so far and thank you for releasing this! I am running into an issue, though, after calling the Launch Mind Maker node but before the receive actions or receive observations are called:

```
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\socketio\server.py", line 679, in _handle_event_internal
  File "site-packages\socketio\server.py", line 708, in _trigger_event
  File "mindmaker.py", line 271, in recieve
KeyError: 'done'
```

It seems to have something to do with how I package my parameter structure. I've tried to keep this as close to the cartpole example as possible but I may have missed something vital. I tried to look for the mindmaker.py source code but as it seems to be unavailable I'm posting here.

Any help is much appreciated!

**Comment by mattgallivan** [comment]
I found the solution to this, of course, minutes after posting. I'm missing the Boolean done in my structure. Thanks!

**Comment by mattgallivan** [comment]
Just to update with a similar issue. Everything is running fine (training a-okay) but if I use custom parameters for A2C (or any of the algorithms), the `max_grad_norm` key is serialized only as `max` and causes an error.
