### ISSUE TITLE
What does mindmaker showing the error while launching it? 

### ISSUE THREAD

**Issue by Devanshu-singh-VR** [krumiaa/MindMaker#29]
I am trying to build a basic RL project with mindmaker plugin. The project contains an agent and a target, agent goal is to reach the target by taking (up, down, left, right) action and the agent will get a reward (+10) when it reaches the target otherwise -1 reward on each action. Ball is an agent and cube is the target in the project. 

I am sharing the same project, if someone wants to download it to check the error. The structure of blueprint is very much similar to the inbuilt cartpole project. Kindly have a look.

I am using UE5.1. 

https://drive.google.com/file/d/1SSVsYukVMrxQ076r3BdY0aI6KCM92pfI/view?usp=share_link

**While launching the mindmaker this error is coming.** 

```
MindMaker running, waiting for Unreal Engine to connect
(6564) wsgi starting up on http://0.0.0.0:3000
(6564) accepted ('127.0.0.1', 51323)
Connected To Unreal Engine
False
4
discrete action space
C:\Users\aiina\Documents\Unreal Projects\Rl_test\Content\MindMaker\dist\mindmaker\gym\spaces\box.py:74: UserWarning: WARN: Box bound precision lowered by casting to float32
save model value: true
load model value: false
Total Training Episodes: 1000
alg selected: PPO
use custom: true
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "site-packages\socketio\server.py", line 720, in _handle_event_internal
  File "site-packages\socketio\server.py", line 745, in _trigger_event
  File "MindMakerDRLStableBv3.py", line 606, in recieve
  File "ast.py", line 46, in literal_eval
  File "ast.py", line 35, in parse
  File "<unknown>", line 0

    ^
SyntaxError: unexpected EOF while parsing

```

What is going wrong in the project? 
How to solve it?

**Comment by Devanshu-singh-VR** [comment]
I figured out that my custom event is not working. While I switch on the play button the lunch mindmaker starts but an event (custom event) I created for the simulation is not working. 

 
![Screenshot (13)](https://user-images.githubusercontent.com/75822824/222666185-6de35db9-c05a-4a43-a20c-a2f94114e13e.png)

![Screenshot (12)](https://user-images.githubusercontent.com/75822824/222666217-c48edebb-7acd-4990-8040-f0a91df12a78.png)

**Comment by krumiaa** [comment]
Ok so you got it figured out? Can we close the issue on github?

**Comment by Devanshu-singh-VR** [comment]
No, I haven't find the solution of the problem. Don't close the issue. Kindly let me know the solution.
